baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'BlackCoral'
theme = 'blowfish'
defaultAppearance = 'dark'

[imaging]
  resampleFilter = "lanczos"
  quality = 100
  anchor = "smart"

[author]
  name = "BlackCoral"
  image = "logo.jpg"
  headline = "Developing stuff"
